language:
  - python

matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: 3.2
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: osx
      env: TRAVIS_PYTHON_VERSION="2"
    - os: osx
      env: TRAVIS_PYTHON_VERSION="3"


before_install:
 # OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated castxml || brew upgrade castxml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 2 ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 3 ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 3 ]]; then sudo ln -s /usr/local/bin/pip3 /usr/local/bin/pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ ${TRAVIS_PYTHON_VERSION:0:1} -eq 3 ]]; then sudo ln -s /usr/local/bin/python3 /usr/local/bin/python; fi

  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gccxml; fi

  # Install pep8, needed by the unit tests
  - pip install pep8

  # Install coverage tools (On 3.2 the new coverage is broken, use an old one)
  # https://github.com/menegazzo/travispy/issues/20
  - if [ $TRAVIS_PYTHON_VERSION == 3.2 ];
    then pip install 'coverage<4.0'; else
    pip install coverage;
    fi
  - pip install coveralls

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi

script:
  - echo $TRAVIS_OS_NAME

  # Modify sitecustomize.py file for coverage. Allows to cover files run in a subprocess.
  - touch "/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/lib/python${TRAVIS_PYTHON_VERSION}/sitecustomize.py"
  - printf "import coverage\ncoverage.process_startup()\n" > "/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/lib/python${TRAVIS_PYTHON_VERSION}/sitecustomize.py"
  # Install pygccxml
  - python setup.py install
  # Run the tests with coverage
  - coverage run unittests/test_all.py
  # Combine multiple .coverage files (we have multiple files because some scripts were run in a subprocess).
  - coverage combine

after_success:
  # Send coverage result to https://coveralls.io/r/gccxml/pygccxml
  - coveralls
